mqtt:
  enabled: false

cameras:
  usb_camera:
    ffmpeg:
      inputs:
        - path: rtsp://host.docker.internal:8554/mystream
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 5

version: 0.15-1
