mqtt:
  enabled: false

cameras:
  cameraDefault1:
    ffmpeg:
      inputs:
        - path: rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 5
      
version: 0.15-1
