mqtt:
  enabled: false

cameras:
  cameraDefault1:
    ffmpeg:
      inputs:
        - path: rtsp://184.72.239.149/vod/mp4:BigBuckBunny_175k.mov
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 5

version: 0.15-1
