services:
  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant
    volumes:
      - /home/dioni/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=America/Sao_Paulo
    restart: unless-stopped
    network_mode: host

  # frigate:
  #   container_name: frigate
  #   image: blakeblackshear/frigate:stable
  #   privileged: true
  #   restart: unless-stopped
  #   shm_size: "512mb"
  #   ports:
  #     - "5000:5000"
  #   volumes:
  #     - ./frigate/config:/config
  #     - ./frigate/media:/media/frigate
  #     - /etc/localtime:/etc/localtime:ro
  #     - type: tmpfs
  #       target: /tmp/cache
  #       tmpfs:
  #         size: 64M
  #   environment:
  #     FRIGATE_RTSP_PASSWORD: "1234"

  # rtsp-server:
  #   container_name: rtsp-server
  #   image: aler9/rtsp-simple-server
  #   ports:
  #     - "8554:8554"
  #   restart: unless-stopped

